export const ActionTypes = {
  GET_ODDS: "GET_ODDS",
  BET_SLIP: "BET_SLIP",
  BET_PARLAY_SLIP: "BET_PARLAY_SLIP",
  GET_LEAGUES_GAMES: "GET_LEAGUES_GAMES",
  GET_UPCOMING_LEAGUES_GAMES: "GET_UPCOMING_LEAGUES_GAMES",
  GET_BALANCE: "GET_BALANCE",
  SET_TAB: "SET_TAB"
};
